version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"